import { describe, expect, test } from 'vitest'

import {
  compileAndRenderClassificationArtifact,
  runClassificationGenerator,
} from './generate-classification-model.js'

describe('classification model generator', () => {
  // Full classification compilation and serialization can exceed Vitest's 5s default on remote runners.
  test(
    'renders deterministic browser-neutral bytes',
    () => {
      const first = compileAndRenderClassificationArtifact()
      expect(compileAndRenderClassificationArtifact()).toBe(first)
      expect(first).toContain('Generated by npm run classification-model:generate')
      expect(first).not.toMatch(/node:|generatedAt|\/Users\/|\/private\//)
    },
    15_000,
  )

  test('finds the committed artifact current', async () => {
    await expect(runClassificationGenerator({ mode: 'check' })).resolves.toBe('current')
  })
})
