import { describe, expect, test } from 'vitest'

import {
  compileAndRenderClassificationArtifact,
  runClassificationGenerator,
} from './generate-classification-model.js'

describe('classification model generator', () => {
  test('renders deterministic browser-neutral bytes', () => {
    const first = compileAndRenderClassificationArtifact()
    expect(compileAndRenderClassificationArtifact()).toBe(first)
    expect(first).toContain('Generated by npm run classification-model:generate')
    expect(first).not.toMatch(/node:|generatedAt|\/Users\/|\/private\//)
  })

  test('finds the committed artifact current', async () => {
    await expect(runClassificationGenerator({ mode: 'check' })).resolves.toBe('current')
  })
})
