import type { CompiledStyleModel } from '../../contracts/style-model.js'
import { stableValue } from '../stable-json.js'

export function renderStyleArtifact(model: CompiledStyleModel): string {
  const value = JSON.stringify(stableValue(model), null, 2)
  return [
    '/* Generated by npm run styles:generate. Do not edit. */',
    "import type { CompiledStyleModel } from '../contracts/style-model.js'",
    "import { deepFreeze } from '../contracts/deep-freeze.js'",
    '',
    `const compiledStyleModel = ${value} as const satisfies CompiledStyleModel`,
    '',
    'export const styleModel = deepFreeze(compiledStyleModel)',
    '',
  ].join('\n')
}
