import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import ts from 'typescript'
import { describe, expect, test } from 'vitest'

import type { CompiledStyleModel } from '../../contracts/style-model.js'
import { questionModel } from '../../generated/question-model.js'
import { styleDefinitionBundle } from '../../definitions/styles/index.js'
import { compileStyles } from './compile.js'
import { renderStyleArtifact } from './serialize.js'
import { stableValue } from '../stable-json.js'

const acceptedHashes = {
  sourceHash: '1ed1b65c6279edb23965965437dc7ef3ca1196e95e2cbf45347ec0d88d303eff',
  semanticHash: '9fb9832c434b22fcd8397809b14117a47c358a266694df24ba68fd290fc5f585',
  dataVersion: 'c5b3b3353b42618875f1c20d64449ec513601b60215351f757dbd1e48d1fee28',
} as const

const generatedArtifactPath = fileURLToPath(
  new URL('../../generated/style-model.ts', import.meta.url),
)
const serializerPath = fileURLToPath(new URL('./serialize.ts', import.meta.url))
const compilerEntrypointPath = fileURLToPath(new URL('../index.ts', import.meta.url))

function compileProductionModel(): CompiledStyleModel {
  const result = compileStyles(
    styleDefinitionBundle,
    questionModel,
    styleDefinitionBundle.sourceFile,
  )
  if (!result.ok) {
    throw new Error(`production style definitions must compile: ${JSON.stringify(result.diagnostics)}`)
  }
  return result.model
}

function reverseObjectInsertion(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(reverseObjectInsertion)
  if (typeof value !== 'object' || value === null) return value
  return Object.fromEntries(
    Object.entries(value)
      .reverse()
      .map(([key, nested]) => [key, reverseObjectInsertion(nested)]),
  )
}

function exportedNames(sourceText: string) {
  const source = ts.createSourceFile(
    'index.ts',
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  )
  const values: string[] = []
  const types: string[] = []
  for (const statement of source.statements) {
    if (!ts.isExportDeclaration(statement) || !statement.exportClause
      || !ts.isNamedExports(statement.exportClause)) continue
    for (const element of statement.exportClause.elements) {
      const target = statement.isTypeOnly || element.isTypeOnly ? types : values
      target.push(element.name.text)
    }
  }
  return { values: values.sort(), types: types.sort() }
}

const productionModel = compileProductionModel()
const productionArtifact = renderStyleArtifact(productionModel)

describe('style artifact serialization', () => {
  test('renders the exact complete deterministic TypeScript module', () => {
    const value = JSON.stringify(stableValue(productionModel), null, 2)
    const expected = [
      '/* Generated by npm run styles:generate. Do not edit. */',
      "import type { CompiledStyleModel } from '../contracts/style-model.js'",
      "import { deepFreeze } from '../contracts/deep-freeze.js'",
      '',
      `const compiledStyleModel = ${value} as const satisfies CompiledStyleModel`,
      '',
      'export const styleModel = deepFreeze(compiledStyleModel)',
      '',
    ].join('\n')

    expect(productionArtifact).toBe(expected)
    expect(productionArtifact.endsWith('\n')).toBe(true)
    expect(productionArtifact.endsWith('\n\n')).toBe(false)
    expect(productionArtifact.split('\n').filter((line) => /\s+$/.test(line))).toEqual([])
  })

  test('is byte-identical across repeated renders and object insertion order', () => {
    const insertionReversed = reverseObjectInsertion(productionModel) as CompiledStyleModel

    expect(renderStyleArtifact(productionModel)).toBe(productionArtifact)
    expect(renderStyleArtifact(productionModel)).toBe(productionArtifact)
    expect(renderStyleArtifact(insertionReversed)).toBe(productionArtifact)
  })

  test('fixes object keys while retaining the canonical model array order', () => {
    expect(productionArtifact.indexOf('  "exclusionTags"')).toBeLessThan(
      productionArtifact.indexOf('  "inventory"'),
    )
    expect(productionArtifact.indexOf('  "inventory"')).toBeLessThan(
      productionArtifact.indexOf('  "metadata"'),
    )
    expect(productionArtifact.indexOf('  "metadata"')).toBeLessThan(
      productionArtifact.indexOf('  "styles"'),
    )
    const stylesSource = productionArtifact.slice(productionArtifact.indexOf('  "styles":'))
    const [firstStyle, secondStyle] = productionModel.styles
    const [firstCore, secondCore] = firstStyle!.cores
    expect(stylesSource.indexOf(`      "id": "${firstStyle!.id}"`)).toBeLessThan(
      stylesSource.indexOf(`      "id": "${secondStyle!.id}"`),
    )
    expect(stylesSource.indexOf(`          "id": "${firstCore!.id}"`)).toBeLessThan(
      stylesSource.indexOf(`          "id": "${secondCore!.id}"`),
    )
  })

  test('preserves the accepted hashes and complete inventory', () => {
    expect(productionModel.metadata).toMatchObject(acceptedHashes)
    expect(productionArtifact).toContain(`"sourceHash": "${acceptedHashes.sourceHash}"`)
    expect(productionArtifact).toContain(`"semanticHash": "${acceptedHashes.semanticHash}"`)
    expect(productionArtifact).toContain(`"dataVersion": "${acceptedHashes.dataVersion}"`)
    expect(productionModel.styles).toHaveLength(18)
    expect(productionModel.styles.flatMap(({ cores }) => cores)).toHaveLength(54)
    expect(productionModel.styles.flatMap(({ cores }) => (
      cores.flatMap(({ subtypes }) => subtypes)
    ))).toHaveLength(270)
    expect(productionModel.styles.flatMap(({ cores }) => (
      cores.flatMap(({ rules }) => rules)
    ))).toHaveLength(378)
    expect(productionModel.styles.flatMap(({ adjustments }) => adjustments)).toHaveLength(25)
    expect(productionModel.inventory).toHaveLength(342)
  })

  test('contains only the approved inert artifact imports and shared freeze boundary', () => {
    const imports = productionArtifact.match(/^import .+$/gm) ?? []
    expect(imports).toEqual([
      "import type { CompiledStyleModel } from '../contracts/style-model.js'",
      "import { deepFreeze } from '../contracts/deep-freeze.js'",
    ])
    expect(imports.join('\n')).not.toMatch(
      /compiler|definitions|\bzod\b|node:|tools\/|persistence|scoring|eligibility|react|localStorage/i,
    )
    expect(productionArtifact).not.toMatch(
      /compileStyles|proveStyleModel|process\.|generatedAt|timestamp|commitSha|\/Users\/|\/private\/|\/tmp\//,
    )
    expect(productionArtifact).toContain(
      'export const styleModel = deepFreeze(compiledStyleModel)',
    )
  })

  test('the package serializer is pure and contains no file, process, clock, or random I/O', async () => {
    const source = await readFile(serializerPath, 'utf8')

    expect(source).not.toMatch(/node:(fs|path|crypto|url)/)
    expect(source).not.toMatch(/readFile|writeFile|rename|unlink|process\.|Date\.|Math\.random/)
    expect(source).not.toMatch(/compileStyles|proveStyleModel/)
  })

  test('the committed artifact is exactly the serializer output', async () => {
    await expect(readFile(generatedArtifactPath, 'utf8')).resolves.toBe(productionArtifact)
  })

  test('exports only a deeply frozen inert styleModel value', async () => {
    const artifact = await import('../../generated/style-model.js')
    const model = artifact.styleModel

    expect(Object.keys(artifact)).toEqual(['styleModel'])
    expect(Object.isFrozen(model)).toBe(true)
    expect(Object.isFrozen(model.metadata)).toBe(true)
    expect(Object.isFrozen(model.exclusionTags)).toBe(true)
    expect(Object.isFrozen(model.inventory)).toBe(true)
    expect(Object.isFrozen(model.styles)).toBe(true)
    expect(Object.isFrozen(model.styles[0])).toBe(true)
    expect(Object.isFrozen(model.styles[0]!.cores)).toBe(true)
    expect(Object.isFrozen(model.styles[0]!.cores[0]!.rules)).toBe(true)
    expect(Object.isFrozen(model.styles[0]!.cores[0]!.subtypes)).toBe(true)
  })
})

describe('Task 10 compiler and runtime boundaries', () => {
  test('has the exact approved compiler value and type export lists', async () => {
    const compilerSource = await readFile(compilerEntrypointPath, 'utf8')
    const compiler = await import('../index.js')
    const names = exportedNames(compilerSource)
    const expectedValues = [
      'DiagnosticCollector',
      'classificationDefinition',
      'compareCodePoints',
      'compileClassification',
      'compileQuestions',
      'compileStyles',
      'definitionBundleSchema',
      'parseDefinitionBundle',
      'questionDefinitionSourceSchema',
      'questionDefinitions',
      'renderQuestionArtifact',
      'renderStyleArtifact',
      'stableJson',
      'styleDefinitionBundle',
      'styleDefinitionBundleSchema',
      'styleDefinitionSchema',
      'styleDefinitions',
      'styleTaxonomy',
    ].sort()
    const expectedTypes = [
      'AdjustmentConditionDefinition',
      'AllowedOptionDecisionRow',
      'AllowedOptionSelection',
      'BonusDefinition',
      'ClassificationModel',
      'CompiledAdjustment',
      'CompiledAdjustmentCondition',
      'CompiledBonus',
      'CompiledConflict',
      'CompiledCore',
      'CompiledExclusionTag',
      'CompiledOption',
      'CompiledQuestion',
      'CompiledQuestionModel',
      'CompiledQuestionModelMetadata',
      'CompiledRuleTarget',
      'CompiledStyle',
      'CompiledStyleInventoryRecord',
      'CompiledStyleModel',
      'CompiledStyleModelMetadata',
      'CompiledStyleRule',
      'CompiledSubtype',
      'CompileQuestionsResult',
      'CompileResult',
      'CompileStylesResult',
      'ConceptKey',
      'ConceptKind',
      'ConceptRecord',
      'ConflictDefinition',
      'CoreId',
      'DefinitionBundleSource',
      'Diagnostic',
      'ExclusionTagId',
      'IntensityId',
      'IntensityOverrideDefinition',
      'MatchTier',
      'NoodleId',
      'OptionDefinitionSource',
      'QuestionDefinitionSource',
      'RuleId',
      'SerializableCondition',
      'StyleDefinition',
      'StyleDefinitionBundleSource',
      'StyleFamilyId',
      'StyleId',
      'StyleRuleDefinition',
      'StyleRuleProvenance',
      'StyleRuleTierDefinition',
      'StyleSourceReference',
      'StyleTaxonomyDefinition',
      'SubtypeId',
    ].sort()

    expect(Object.keys(compiler).sort()).toEqual(expectedValues)
    expect(names.values).toEqual(expectedValues)
    expect(names.types).toEqual(expectedTypes)
  })

  test('does not expose proof or staged compiler internals', async () => {
    const compiler = await import('../index.js')
    const compilerSource = await readFile(compilerEntrypointPath, 'utf8')

    expect(compiler).not.toHaveProperty('proveStyleModel')
    expect(compilerSource).not.toMatch(
      /\b(proveStyleModel|StyleCoreStage|StyleSubtypeStage|StyleRulesStage|ResolvedStyleCoreRule)\b/,
    )
  })

  test('leaves the runtime root exact and does not publish the style artifact early', async () => {
    const runtime = await import('../../index.js')

    expect(Object.keys(runtime).sort()).toEqual([
      'applyAnswer',
      'createStoredClassificationPayloadV1',
      'decodeAnswerDraft',
      'evaluateFlow',
      'getFirstActionableQuestion',
      'getNextInteractiveQuestion',
      'getPreviousInteractiveQuestion',
      'questionModel',
      'restoreClassification',
      'updatePendingSelection',
    ].sort())
    expect(runtime).not.toHaveProperty('styleModel')
    expect(runtime).not.toHaveProperty('compileStyles')
  })
})
