import type { DefinitionBundleSource } from '../compiler/source-schema.js'

const sourceFile = 'packages/classification-core/src/definitions/questions.ts'

// Migrated from legacy src/data/questions.json and src/domain/questionRules.ts at eebf00b.
// legacyWeight is opaque legacy metadata; scoring semantics belong to Batch 3B.
export const questionDefinitions: DefinitionBundleSource['questions'] = [
  {
    sourceFile,
    id: 'form',
    messageId: 'question-form',
    order: 0,
    selectionType: 'single',
    minSelections: 1,
    maxSelections: 1,
    legacyWeight: 16,
    dependsOn: [],
    autoSelectSingleOption: false,
    optionSet: {
      kind: 'flat',
      options: [
        { id: 'soup', messageId: 'option-form-soup' },
        { id: 'tsukemen', messageId: 'option-form-tsukemen' },
        { id: 'dry', messageId: 'option-form-dry' },
      ],
    },
  },
  {
    sourceFile,
    id: 'archetype',
    messageId: 'question-archetype',
    order: 1,
    selectionType: 'single',
    minSelections: 1,
    maxSelections: 1,
    legacyWeight: 16,
    dependsOn: ['form'],
    autoSelectSingleOption: false,
    optionSet: {
      kind: 'branch',
      by: 'form',
      branches: [
        {
          when: 'soup',
          options: [
            { id: 'chintan', messageId: 'option-archetype-chintan' },
            { id: 'paitan', messageId: 'option-archetype-paitan' },
          ],
        },
        {
          when: 'tsukemen',
          options: [
            { id: 'konbusui-light', messageId: 'option-archetype-konbusui-light' },
            { id: 'gyokai-rich', messageId: 'option-archetype-gyokai-rich' },
            { id: 'miso-rich', messageId: 'option-archetype-miso-rich' },
            { id: 'tsukemen-other', messageId: 'option-archetype-tsukemen-other' },
          ],
        },
        {
          when: 'dry',
          options: [
            { id: 'aburasoba', messageId: 'option-archetype-aburasoba' },
            { id: 'taiwan-mazesoba', messageId: 'option-archetype-taiwan-mazesoba' },
            { id: 'soupless-tantan', messageId: 'option-archetype-soupless-tantan' },
            { id: 'dry-other', messageId: 'option-archetype-dry-other' },
          ],
        },
      ],
    },
  },
  {
    sourceFile,
    id: 'tare',
    messageId: 'question-tare',
    order: 2,
    selectionType: 'single',
    minSelections: 1,
    maxSelections: 1,
    legacyWeight: 15,
    dependsOn: ['archetype'],
    autoSelectSingleOption: true,
    optionSet: {
      kind: 'flat',
      options: [
        { id: 'shoyu', messageId: 'option-tare-shoyu' },
        { id: 'shio', messageId: 'option-tare-shio' },
        { id: 'miso', messageId: 'option-tare-miso' },
        { id: 'spicy-sesame', messageId: 'option-tare-spicy-sesame' },
        { id: 'none', messageId: 'option-tare-none' },
      ],
    },
    restriction: {
      by: 'archetype',
      allow: [
        { when: 'konbusui-light', optionIds: ['shio', 'shoyu'] },
        { when: 'gyokai-rich', optionIds: ['shoyu', 'shio', 'miso'] },
        { when: 'miso-rich', optionIds: ['miso'] },
        { when: 'aburasoba', optionIds: ['shoyu', 'none'] },
        { when: 'taiwan-mazesoba', optionIds: ['spicy-sesame', 'shoyu', 'none'] },
        { when: 'soupless-tantan', optionIds: ['spicy-sesame'] },
      ],
    },
  },
  {
    sourceFile,
    id: 'source',
    messageId: 'question-source',
    order: 3,
    selectionType: 'multiple',
    minSelections: 1,
    maxSelections: 2,
    legacyWeight: 18,
    dependsOn: ['archetype'],
    autoSelectSingleOption: true,
    optionSet: {
      kind: 'flat',
      options: [
        { id: 'pork', messageId: 'option-source-pork' },
        { id: 'chicken', messageId: 'option-source-chicken' },
        { id: 'duck', messageId: 'option-source-duck' },
        { id: 'beef', messageId: 'option-source-beef' },
        { id: 'fish-seafood', messageId: 'option-source-fish-seafood' },
        { id: 'shellfish', messageId: 'option-source-shellfish' },
        { id: 'shrimp-crab', messageId: 'option-source-shrimp-crab' },
        { id: 'vegetable', messageId: 'option-source-vegetable' },
        { id: 'mixed', messageId: 'option-source-mixed' },
        { id: 'unsure', messageId: 'option-source-unsure', exclusive: true },
      ],
    },
    restriction: {
      by: 'archetype',
      allow: [
        { when: 'konbusui-light', optionIds: ['fish-seafood', 'shellfish', 'vegetable', 'mixed', 'unsure'] },
        { when: 'gyokai-rich', optionIds: ['fish-seafood', 'shellfish', 'mixed', 'unsure'] },
        { when: 'miso-rich', optionIds: ['pork', 'chicken', 'fish-seafood', 'vegetable', 'mixed', 'unsure'] },
        { when: 'aburasoba', optionIds: ['pork', 'mixed', 'unsure'] },
        { when: 'taiwan-mazesoba', optionIds: ['pork', 'mixed', 'unsure'] },
        { when: 'soupless-tantan', optionIds: ['pork', 'vegetable', 'mixed', 'unsure'] },
      ],
    },
  },
  {
    sourceFile,
    id: 'body',
    messageId: 'question-body',
    order: 4,
    selectionType: 'single',
    minSelections: 1,
    maxSelections: 1,
    legacyWeight: 14,
    dependsOn: ['archetype'],
    autoSelectSingleOption: true,
    optionSet: {
      kind: 'flat',
      options: [
        { id: 'light', messageId: 'option-body-light' },
        { id: 'balanced', messageId: 'option-body-balanced' },
        { id: 'rich', messageId: 'option-body-rich' },
        { id: 'backfat-heavy', messageId: 'option-body-backfat-heavy' },
        { id: 'ultra-heavy', messageId: 'option-body-ultra-heavy' },
      ],
    },
    restriction: {
      by: 'archetype',
      allow: [
        { when: 'konbusui-light', optionIds: ['light', 'balanced'] },
        { when: 'gyokai-rich', optionIds: ['balanced', 'rich', 'ultra-heavy'] },
        { when: 'miso-rich', optionIds: ['balanced', 'rich', 'ultra-heavy'] },
        { when: 'aburasoba', optionIds: ['light', 'balanced', 'rich'] },
        { when: 'taiwan-mazesoba', optionIds: ['balanced', 'rich', 'ultra-heavy'] },
        { when: 'soupless-tantan', optionIds: ['balanced', 'rich', 'ultra-heavy'] },
      ],
    },
  },
  {
    sourceFile,
    id: 'noodle',
    messageId: 'question-noodle',
    order: 5,
    selectionType: 'single',
    minSelections: 1,
    maxSelections: 1,
    legacyWeight: 11,
    dependsOn: ['archetype'],
    autoSelectSingleOption: true,
    optionSet: {
      kind: 'flat',
      options: [
        { id: 'thin-straight', messageId: 'option-noodle-thin-straight' },
        { id: 'medium-thin-straight', messageId: 'option-noodle-medium-thin-straight' },
        { id: 'medium-thick-straight', messageId: 'option-noodle-medium-thick-straight' },
        { id: 'medium-thick-wavy', messageId: 'option-noodle-medium-thick-wavy' },
        { id: 'extra-thick', messageId: 'option-noodle-extra-thick' },
      ],
    },
    restriction: {
      by: 'archetype',
      allow: [
        { when: 'konbusui-light', optionIds: ['medium-thin-straight', 'medium-thick-straight'] },
        { when: 'gyokai-rich', optionIds: ['medium-thick-straight', 'medium-thick-wavy', 'extra-thick'] },
        { when: 'miso-rich', optionIds: ['medium-thick-straight', 'medium-thick-wavy', 'extra-thick'] },
        { when: 'aburasoba', optionIds: ['medium-thin-straight', 'medium-thick-straight', 'extra-thick'] },
        { when: 'taiwan-mazesoba', optionIds: ['medium-thick-straight', 'extra-thick'] },
        { when: 'soupless-tantan', optionIds: ['medium-thick-straight', 'extra-thick'] },
      ],
    },
  },
  {
    sourceFile,
    id: 'signature',
    messageId: 'question-signature',
    order: 6,
    selectionType: 'multiple',
    minSelections: 1,
    maxSelections: 2,
    legacyWeight: 10,
    dependsOn: ['archetype'],
    autoSelectSingleOption: true,
    optionSet: {
      kind: 'flat',
      options: [
        { id: 'nori-spinach', messageId: 'option-signature-nori-spinach' },
        { id: 'corn-butter', messageId: 'option-signature-corn-butter' },
        { id: 'bean-sprout-garlic-backfat', messageId: 'option-signature-bean-sprout-garlic-backfat' },
        { id: 'fish-kombu', messageId: 'option-signature-fish-kombu' },
        { id: 'yuzu-citrus', messageId: 'option-signature-yuzu-citrus' },
        { id: 'no-preference', messageId: 'option-signature-no-preference', exclusive: true },
      ],
    },
    restriction: {
      by: 'archetype',
      allow: [
        { when: 'konbusui-light', optionIds: ['fish-kombu', 'yuzu-citrus', 'no-preference'] },
        { when: 'gyokai-rich', optionIds: ['fish-kombu', 'no-preference'] },
        { when: 'miso-rich', optionIds: ['corn-butter', 'fish-kombu', 'no-preference'] },
        { when: 'aburasoba', optionIds: ['no-preference', 'bean-sprout-garlic-backfat', 'fish-kombu'] },
        { when: 'taiwan-mazesoba', optionIds: ['fish-kombu', 'bean-sprout-garlic-backfat', 'no-preference'] },
        { when: 'soupless-tantan', optionIds: ['no-preference', 'bean-sprout-garlic-backfat'] },
      ],
    },
  },
  {
    sourceFile,
    id: 'exclusions',
    messageId: 'question-exclusions',
    order: 7,
    selectionType: 'multiple',
    minSelections: 1,
    maxSelections: 8,
    legacyWeight: 0,
    dependsOn: [],
    autoSelectSingleOption: false,
    emptyFallbackOptionId: 'none',
    optionSet: {
      kind: 'flat',
      options: [
        { id: 'pork', messageId: 'option-exclusions-pork' },
        { id: 'chicken', messageId: 'option-exclusions-chicken' },
        { id: 'duck', messageId: 'option-exclusions-duck' },
        { id: 'beef', messageId: 'option-exclusions-beef' },
        { id: 'fish-seafood', messageId: 'option-exclusions-fish-seafood' },
        { id: 'shellfish', messageId: 'option-exclusions-shellfish' },
        { id: 'shrimp-crab', messageId: 'option-exclusions-shrimp-crab' },
        { id: 'dairy', messageId: 'option-exclusions-dairy' },
        { id: 'none', messageId: 'option-exclusions-none', exclusive: true },
      ],
    },
  },
]
