import type { MigrationLedger } from './ledger-schema.js'

export function compareCodePoints(left: string, right: string) {
  const leftPoints = Array.from(left, (character) => character.codePointAt(0)!)
  const rightPoints = Array.from(right, (character) => character.codePointAt(0)!)
  const sharedLength = Math.min(leftPoints.length, rightPoints.length)
  for (let index = 0; index < sharedLength; index += 1) {
    const difference = leftPoints[index]! - rightPoints[index]!
    if (difference !== 0) return difference
  }
  return leftPoints.length - rightPoints.length
}

export function renderLedger(ledger: MigrationLedger) {
  const sections = [...ledger.entries]
    .sort((left, right) => compareCodePoints(left.batch, right.batch))
    .flatMap((entry) => [
      `## Batch ${entry.batch} — ${entry.status}`,
      '',
      `- Behavior: \`${entry.behavior}\``,
      `- Transformation: ${entry.transformation}`,
      ...(entry.foundationCommit ? [`- Foundation commit: \`${entry.foundationCommit}\``] : []),
      '',
      '### Legacy sources',
      '',
      ...(entry.legacySources.length
        ? [...entry.legacySources].sort(compareCodePoints).map((source) => `- \`${source}\``)
        : ['- None; this batch introduces new infrastructure.']),
      '',
      '### New owners',
      '',
      ...[...entry.newOwners].sort(compareCodePoints).map((owner) => `- \`${owner}\``),
      '',
      '### Verification',
      '',
      ...(entry.verification.length
        ? [...entry.verification]
            .sort((left, right) => compareCodePoints(left.gate, right.gate))
            .flatMap((item) => [
              `- \`${item.gate}\`: \`${item.command}\` — ${item.outcome}; ${item.evidence}`,
              ...(item.commitSha ? [`  - Commit: \`${item.commitSha}\``] : []),
              ...(item.runUrl ? [`  - Run: ${item.runUrl}`] : []),
            ])
        : ['- Pending.']),
      '',
    ])
  return [
    '# Migration Ledger',
    '',
    '> Generated from `docs/migration/ledger.json`. Do not edit this file directly.',
    '',
    `Baseline: \`${ledger.baseline.repository}@${ledger.baseline.commit}\``,
    '',
    ...sections,
  ].join('\n')
}
