import { compareCodePoints } from '@ramen-style/classification-core/compiler'

import type { MigrationLedger } from './ledger-schema.js'

export function renderLedger(ledger: MigrationLedger) {
  const sections = [...ledger.entries]
    .sort((left, right) => compareCodePoints(left.batch, right.batch))
    .flatMap((entry) => [
      `## Batch ${entry.batch} — ${entry.status}`,
      '',
      `- Behavior: \`${entry.behavior}\``,
      `- Transformation: ${entry.transformation}`,
      ...(entry.foundationCommit ? [`- Foundation commit: \`${entry.foundationCommit}\``] : []),
      ...(entry.implementationSha ? [`- Implementation SHA: \`${entry.implementationSha}\``] : []),
      '',
      '### Legacy sources',
      '',
      ...(entry.legacySources.length
        ? [...entry.legacySources].sort(compareCodePoints).map((source) => `- \`${source}\``)
        : ['- None; this batch introduces new infrastructure.']),
      '',
      '### New owners',
      '',
      ...[...entry.newOwners].sort(compareCodePoints).map((owner) => `- \`${owner}\``),
      '',
      ...(entry.semanticPaths?.length ? [
        '### Semantic paths',
        '',
        ...entry.semanticPaths.map((path) => `- \`${path}\``),
        '',
      ] : []),
      ...(entry.incidents ? [
        '### Incidents',
        '',
        ...(entry.incidents.length
          ? entry.incidents.map((incident) => `- \`${incident}\``)
          : ['- None recorded.']),
        '',
      ] : []),
      '### Verification',
      '',
      ...(entry.verification.length
        ? [...entry.verification]
            .sort((left, right) => compareCodePoints(left.gate, right.gate))
            .flatMap((item) => [
              `- \`${item.gate}\`: \`${item.command}\` — ${item.outcome}; ${item.evidence}`,
              ...(item.commitSha ? [`  - Commit: \`${item.commitSha}\``] : []),
              ...(item.runUrl ? [`  - Run: ${item.runUrl}`] : []),
            ])
        : ['- Pending.']),
      '',
    ])
  return [
    '# Migration Ledger',
    '',
    '> Generated from `docs/migration/ledger.json`. Do not edit this file directly.',
    '',
    `Baseline: \`${ledger.baseline.repository}@${ledger.baseline.commit}\``,
    '',
    ...sections,
  ].join('\n')
}
