import type { MigrationLedger } from './ledger-schema.js'

export function renderLedger(ledger: MigrationLedger) {
  const sections = [...ledger.entries]
    .sort((left, right) => left.batch.localeCompare(right.batch, undefined, { numeric: true }))
    .flatMap((entry) => [
      `## Batch ${entry.batch} — ${entry.status}`,
      '',
      `- Behavior: \`${entry.behavior}\``,
      `- Transformation: ${entry.transformation}`,
      ...(entry.foundationCommit ? [`- Foundation commit: \`${entry.foundationCommit}\``] : []),
      '',
      '### Legacy sources',
      '',
      ...(entry.legacySources.length
        ? [...entry.legacySources].sort().map((source) => `- \`${source}\``)
        : ['- None; this batch introduces new infrastructure.']),
      '',
      '### New owners',
      '',
      ...[...entry.newOwners].sort().map((owner) => `- \`${owner}\``),
      '',
      '### Verification',
      '',
      ...(entry.verification.length
        ? [...entry.verification]
            .sort((left, right) => left.gate.localeCompare(right.gate))
            .flatMap((item) => [
              `- \`${item.gate}\`: \`${item.command}\` — ${item.outcome}; ${item.evidence}`,
              ...(item.commitSha ? [`  - Commit: \`${item.commitSha}\``] : []),
              ...(item.runUrl ? [`  - Run: ${item.runUrl}`] : []),
            ])
        : ['- Pending.']),
      '',
    ])
  return [
    '# Migration Ledger',
    '',
    '> Generated from `docs/migration/ledger.json`. Do not edit this file directly.',
    '',
    `Baseline: \`${ledger.baseline.repository}@${ledger.baseline.commit}\``,
    '',
    ...sections,
  ].join('\n')
}
