export { styleModel } from './generated/style-model.js'
export type {
  CompiledAdjustment,
  CompiledAdjustmentCondition,
  CompiledBonus,
  CompiledConflict,
  CompiledCore,
  CompiledExclusionTag,
  CompiledRuleTarget,
  CompiledStyle,
  CompiledStyleInventoryRecord,
  CompiledStyleModel,
  CompiledStyleModelMetadata,
  CompiledStyleRule,
  CompiledSubtype,
  CoreId,
  ExclusionTagId,
  IntensityId,
  MatchTier,
  NoodleId,
  RuleId,
  StyleFamilyId,
  StyleId,
  StyleRuleProvenance,
  StyleSourceReference,
  SubtypeId,
} from './contracts/style-model.js'
