import type { ClassificationModel } from '../../contracts/model.js'
import { stableValue } from '../stable-json.js'

export function renderClassificationArtifact(model: ClassificationModel): string {
  const data = {
    modelVersion: model.modelVersion,
    dataVersion: model.dataVersion,
    provenance: model.provenance,
    policy: model.policy,
    eligibilityPolicy: model.eligibilityPolicy,
    inventory: model.inventory,
  }
  const value = JSON.stringify(stableValue(data), null, 2)
  return [
    '/* Generated by npm run classification-model:generate. Do not edit. */',
    "import type { ClassificationModel } from '../contracts/model.js'",
    "import { deepFreeze } from '../contracts/deep-freeze.js'",
    "import { questionModel } from './question-model.js'",
    "import { styleModel } from './style-model.js'",
    '',
    `const compiledClassificationData = ${value} as const`,
    '',
    'export const classificationModel = deepFreeze({',
    '  ...compiledClassificationData,',
    '  questionModel,',
    '  questions: questionModel.questions,',
    '  styleModel,',
    '} satisfies ClassificationModel)',
    '',
  ].join('\n')
}
